### ISSUE TITLE
Unnecessarily deep list in execStatement return type

### ISSUE THREAD

**Issue by nurpax** [GaloisInc/sqlite#4]
The return type for execStatement seems to use an unnecessarily deep list for the return type.

It now returns [[Row a]].  But a 'Row a' already contains all the result columns & values, so I would expect the return type to be [Row a].  Users of execStatement are now required to peel off one extra list using 'head' or pattern matching.

I must be missing something.  What is the extra nesting used for?  

I put up a sample .hs file that demonstrates this case here: https://gist.github.com/3197006

Thanks.

**Comment by acatton** [comment]
The extra nesting is used to run multiple SQL Statement. Prepared statement in many DBMS are ensured to only have one statement, but not in SQLite.

In SQLite, preparing the statement `"SELECT 1; SELECT 2"` will prepare the statement `SELECT 1` and return a `**pzTail` to the unused portion of the SQL, in this case `" SELECT 2"`.

See [SQLite documentation](https://www.sqlite.org/capi3ref.html#sqlite3_prepare) for further information.

`sqlite` haskel bindings, will consume all prepared statements, and return them in an outer list.

Here's an example test (that I have in figo GmbH repo, but haven't done a pull request for it yet) so that you understand this outer list:

```haskell
        it "can execute multiple statements" $ withTempDB $ \h -> do
            result <- execStatement h "SELECT 1 as a; SELECT 2 as b"
            result `shouldBe` Right [[[("a", "1")]], [[("b", "2")]]]
```

I had to read the code, and understand what it was doing, but like you, I was confused at first, and wanted to remove the nesting.

I will document this.
